In [11]:
import os 
import numpy as np 
import matplotlib.pyplot as plt 
import cv2 
import imutils
import torch 
import torch.nn as nn 
import torch.optim as optim 
from torch.utils.data import DataLoader,Dataset
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import torchvision.transforms as transforms
from torchvision.transforms.functional import to_pil_image
import torchvision.models as models
import torch.nn as nn 
import torch.optim as optim
import torch.nn.functional as F
from torch.optim.lr_scheduler import StepLR
import time
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix,accuracy_score
import seaborn as sns
import cv2
import numpy as np
import torch
from torchvision import transforms
from PIL import Image
import warnings
warnings.filterwarnings("ignore")

In [36]:
def crop_img(img):
    """
    Finds the extreme points on the image and crops the rectangular region.
    """
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    gray = cv2.GaussianBlur(gray, (3, 3), 0)
    thresh = cv2.threshold(gray, 45, 255, cv2.THRESH_BINARY)[1]
    thresh = cv2.erode(thresh, None, iterations=2)
    thresh = cv2.dilate(thresh, None, iterations=2)
    cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    if len(cnts) == 0:
        return img  
    c = max(cnts, key=cv2.contourArea)
    extLeft = tuple(c[c[:, :, 0].argmin()][0])
    extRight = tuple(c[c[:, :, 0].argmax()][0])
    extTop = tuple(c[c[:, :, 1].argmin()][0])
    extBot = tuple(c[c[:, :, 1].argmax()][0])
    ADD_PIXELS = 5
    y1, y2 = max(0, extTop[1] - ADD_PIXELS), min(img.shape[0], extBot[1] + ADD_PIXELS)
    x1, x2 = max(0, extLeft[0] - ADD_PIXELS), min(img.shape[1], extRight[0] + ADD_PIXELS)
    new_img = img[y1:y2, x1:x2].copy()
    return new_img

In [37]:
test_path = "Brain_Tumor_MRI_Dataset\Testing"
class_list = class_list = sorted(os.listdir(test_path))
class_list

['glioma', 'meningioma', 'notumor', 'pituitary']

In [38]:
def preprocess_single_image(image_path, img_size=224):
    """
    Preprocess a single image for inference.
    """
    # Load the image
    img = cv2.imread(image_path)
    if img is None:
        raise ValueError(f"Unable to load image from {image_path}")
    img = crop_img(img)
    img = cv2.resize(img, (img_size, img_size))
    img = cv2.bilateralFilter(img, 2, 50, 50)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = np.uint8(img)
    img = cv2.applyColorMap(img, cv2.COLORMAP_BONE)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img

def prepare_for_inference(img,img_size=224):
    """
    Prepare the preprocessed image for inference by applying transformations and adding a batch dimension.
    """
    transform = transforms.Compose([
        transforms.ToPILImage(),
        transforms.Resize((img_size, img_size)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    img = transform(img)
    img = img.unsqueeze(0)  # Shape: [1, C, H, W]
    return img

def inference_pipeline(image_path, model):
    """
    Pipeline for preprocessing and inference on a single image.
    """
    # Preprocess the image
    img = preprocess_single_image(image_path)

    # Prepare the image for inference
    img_tensor = prepare_for_inference(img)

    # Perform inference
    model.eval()  # Set the model to evaluation mode
    with torch.no_grad():
        output = model(img_tensor)

    # Get the predicted class
    _, predicted_class = torch.max(output, 1)
    predicted_class = predicted_class.item()

    return class_list[predicted_class]

In [39]:
class BrainTumorClassifier(nn.Module):
    def __init__(self, num_classes):
        super(BrainTumorClassifier, self).__init__()
        # Load pre-trained ResNet-50 model with ImageNet weights
        self.base_model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
        
        for param in self.base_model.parameters():
            param.requires_grad = True

        # Replace the final fully connected layer
        in_features = self.base_model.fc.in_features
        self.base_model.fc = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(in_features, num_classes)
        )

    def forward(self, x):
        return self.base_model(x)

In [40]:
model = BrainTumorClassifier(num_classes=4)
model_path = "Model/brain_tumor_classifier_05.pth"
model.load_state_dict(torch.load(model_path,map_location=torch.device('cpu')))
model.eval()

BrainTumorClassifier(
  (base_model): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (downsample): Sequen

In [41]:
import os
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report


dir_path = "Brain_Tumor_MRI_Dataset/Testing"
total_images = 0
correct_predictions = 0

# Lists to store true and predicted labels
true_labels = []
predicted_labels = []

# Iterate through each class and image
for tumor_class in os.listdir(dir_path):
    for image in os.listdir(os.path.join(dir_path, tumor_class)):
        image_path = os.path.join(dir_path, tumor_class, image)
        
        # Get the predicted class
        predicted_class = inference_pipeline(image_path, model)
        predicted_labels.append(predicted_class)
        
        # Get the true class (convert to integer using the mapping)
        original_class = tumor_class
        true_labels.append(original_class)
        
        # Compare predicted and true class
        if predicted_class == original_class:
            correct_predictions += 1
        
        total_images += 1

# Calculate accuracy
accuracy = (correct_predictions / total_images) * 100
print(f"Total Images: {total_images}")
print(f"Correct Predictions: {correct_predictions}")
print(f"Accuracy: {accuracy:.2f}%")

# Compute precision, recall, and F1-score
precision = precision_score(true_labels, predicted_labels, average='weighted')
recall = recall_score(true_labels, predicted_labels, average='weighted')
f1 = f1_score(true_labels, predicted_labels, average='weighted')

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

# Compute confusion matrix
conf_matrix = confusion_matrix(true_labels, predicted_labels)
print("Confusion Matrix:")
print(conf_matrix)

# Generate a classification report
print("Classification Report:")
print(classification_report(true_labels, predicted_labels, target_names=class_list))

Total Images: 1311
Correct Predictions: 504
Accuracy: 38.44%
Precision: 0.4548
Recall: 0.3844
F1-Score: 0.2792
Confusion Matrix:
[[  2 109 187   2]
 [  5  64 236   1]
 [  0   2 403   0]
 [  3   4 258  35]]
Classification Report:
              precision    recall  f1-score   support

      glioma       0.20      0.01      0.01       300
  meningioma       0.36      0.21      0.26       306
     notumor       0.37      1.00      0.54       405
   pituitary       0.92      0.12      0.21       300

    accuracy                           0.38      1311
   macro avg       0.46      0.33      0.26      1311
weighted avg       0.45      0.38      0.28      1311

